# Generated by Django 4.2.7 on 2023-11-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0006_alter_data_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='diff',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
